# AIRPORTS DATA

## 1) MANUAL WAY

BERLIN

In [ ]:
# import libraries
import pandas as pd
import requests

In [ ]:
# get the Airports data 
# use url > make a request > download html

import requests

url = "https://aerodatabox.p.rapidapi.com/airports/iata/BER"

querystring = {"withTime":"false"}

headers = {
	"X-RapidAPI-Key": "b7c3d136e9msh33795cfe77db702p1d08b1jsn1f39bb3b492e",
	"X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
}

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

{"icao":"EDDB","iata":"BER","shortName":"Brandenburg","fullName":"Berlin, Berlin Brandenburg","municipalityName":"Berlin","location":{"lat":52.35139,"lon":13.493889},"country":{"code":"DE","name":"Germany"},"continent":{"code":"EU","name":"Europe"},"timeZone":"Europe/Berlin","urls":{"webSite":"https://ber.berlin-airport.de/","wikipedia":"https://en.wikipedia.org/wiki/Berlin_Brandenburg_Airport","twitter":"http://twitter.com/berlinairport","googleMaps":"https://www.google.com/maps/@52.351389,13.493889,14z","flightRadar":"https://www.flightradar24.com/52.35,13.49/14"}}

In [ ]:
# format scraped data into JSON format
response.json()

{'icao': 'EDDB',
 'iata': 'BER',
 'shortName': 'Brandenburg',
 'fullName': 'Berlin, Berlin Brandenburg',
 'municipalityName': 'Berlin',
 'location': {'lat': 52.35139, 'lon': 13.493889},
 'country': {'code': 'DE', 'name': 'Germany'},
 'continent': {'code': 'EU', 'name': 'Europe'},
 'timeZone': 'Europe/Berlin',
 'urls': {'webSite': 'https://ber.berlin-airport.de/',
  'wikipedia': 'https://en.wikipedia.org/wiki/Berlin_Brandenburg_Airport',
  'twitter': 'http://twitter.com/berlinairport',
  'googleMaps': 'https://www.google.com/maps/@52.351389,13.493889,14z',
  'flightRadar': 'https://www.flightradar24.com/52.35,13.49/14'}}

In [ ]:
# turn this into a dataframe
pd.json_normalize(response.json())

,icao,iata,shortName,fullName,municipalityName,timeZone,location.lat,location.lon,country.code,country.name,continent.code,continent.name,urls.webSite,urls.wikipedia,urls.twitter,urls.googleMaps,urls.flightRadar
0,EDDB,BER,Brandenburg,"Berlin, Berlin Brandenburg",Berlin,Europe/Berlin,52.35139,13.493889,DE,Germany,EU,Europe,https://ber.berlin-airport.de/,https://en.wikipedia.org/wiki/Berlin_Brandenbu...,http://twitter.com/berlinairport,"https://www.google.com/maps/@52.351389,13.4938...","https://www.flightradar24.com/52.35,13.49/14"

## 2) FUNCTIONAL WAY

In [ ]:
# import libraries
import pandas as pd
import requests

In [ ]:
response.json()

{'icao': 'EDDB',
 'iata': 'BER',
 'shortName': 'Brandenburg',
 'fullName': 'Berlin, Berlin Brandenburg',
 'municipalityName': 'Berlin',
 'location': {'lat': 52.35139, 'lon': 13.493889},
 'country': {'code': 'DE', 'name': 'Germany'},
 'continent': {'code': 'EU', 'name': 'Europe'},
 'timeZone': 'Europe/Berlin',
 'urls': {'webSite': 'https://ber.berlin-airport.de/',
  'wikipedia': 'https://en.wikipedia.org/wiki/Berlin_Brandenburg_Airport',
  'twitter': 'http://twitter.com/berlinairport',
  'googleMaps': 'https://www.google.com/maps/@52.351389,13.493889,14z',
  'flightRadar': 'https://www.flightradar24.com/52.35,13.49/14'}}

In [ ]:
def icao_airport_codes(latitudes, longitudes):

  #assert len(latitudes) == len(longitudes)
  
  list_for_df = []

  for i in range(len(latitudes)):

    url = f"https://aerodatabox.p.rapidapi.com/airports/search/location/{latitudes[i]}/{longitudes[i]}/km/100/16"

    querystring = {"withFlightInfoOnly":"true"}

    headers = {
      "X-RapidAPI-Key": "b7c3d136e9msh33795cfe77db702p1d08b1jsn1f39bb3b492e",
      "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
    }
    
    # format scraped data into JSON format
    response = requests.request("GET", url, headers=headers, params=querystring)

    list_for_df.append(pd.json_normalize(response.json()['items']))

  return pd.concat(list_for_df, ignore_index=True)

## AIRPORTS DATAFRAME

In [ ]:
airports_df = icao_airport_codes([52.31, 53.33, 51.30, 41.00, 41.23, 48.51], [13.24, 10.00, 0.7, 28.57, 2.11, 2.21])
airports_df

,icao,iata,name,shortName,municipalityName,countryCode,location.lat,location.lon
0,EDDB,BER,"Berlin, Berlin Brandenburg",Brandenburg,Berlin,DE,52.351390,13.493889
1,EDDH,HAM,Hamburg,Hamburg,Hamburg,DE,53.630400,9.988229
2,EDDW,BRE,Bremen,Bremen,Bremen,DE,53.047500,8.786669
3,EDDV,HAJ,"Hanover, Hannover",Hannover,Hanover,DE,52.461100,9.685079
4,EGMC,SEN,Southend,Southend,Southend,GB,51.571400,0.695555
5,EGLC,LCY,"London, London City",City,London,GB,51.505300,0.055277
6,EGKR,KRH,"Redhill, Redhill Aerodrome",Aerodrome,Redhill,GB,51.213600,-0.138611
7,EGKK,LGW,"London, London Gatwick",Gatwick,London,GB,51.148100,-0.190277
8,EGSS,STN,"London, London Stansted",Stansted,London,GB,51.885000,0.234999
9,EGLL,LHR,"London, London Heathrow",Heathrow,London,GB,51.470600,-0.461941
10,EGGW,LTN,"London, London Luton",Luton,London,GB,51.874700,-0.368333
11,LTFM,IST,Istanbul,Istanbul,Istanbul,TR,41.275276,28.751944
12,LTFJ,SAW,"Istanbul, Sabiha Gökçen",Sabiha Gökçen,Istanbul,TR,40.898600,29.309200
13,LEBL,BCN,Barcelona,Barcelona,Barcelona,ES,41.297100,2.078459
14,LERS,REU,"Reus, Reus Air Base",Air Base,Reus,ES,41.147400,1.167170
15,LEGE,GRO,Girona,Girona,Girona,ES,41.901000,2.760550
16,LFPO,ORY,"Paris, Paris-Orly",-Orly,Paris,FR,48.725300,2.359440
17,LFPB,LBG,"Paris, Paris-Le Bourget",-Le Bourget,Paris,FR,48.969400,2.441390
18,LFPG,CDG,"Paris, Charles de Gaulle",Charles de Gaulle,Paris,FR,49.012800,2.549999

In [ ]:
# select the cities in our list
airports_df = airports_df[airports_df["municipalityName"].isin(['Berlin', 'Hamburg', 'London', 'Istanbul', 'Barcelona'])]

# FLIGHTS DATA

In [ ]:
import pandas as pd
from datetime import datetime, date, timedelta
import requests
from pytz import timezone

## FUNCTIONAL WAY

In [ ]:
response.json()

{'icao': 'EDDB',
 'iata': 'BER',
 'shortName': 'Brandenburg',
 'fullName': 'Berlin, Berlin Brandenburg',
 'municipalityName': 'Berlin',
 'location': {'lat': 52.35139, 'lon': 13.493889},
 'country': {'code': 'DE', 'name': 'Germany'},
 'continent': {'code': 'EU', 'name': 'Europe'},
 'timeZone': 'Europe/Berlin',
 'urls': {'webSite': 'https://ber.berlin-airport.de/',
  'wikipedia': 'https://en.wikipedia.org/wiki/Berlin_Brandenburg_Airport',
  'twitter': 'http://twitter.com/berlinairport',
  'googleMaps': 'https://www.google.com/maps/@52.351389,13.493889,14z',
  'flightRadar': 'https://www.flightradar24.com/52.35,13.49/14'}}

In [ ]:
def tomorrows_flight_arrivals(icao_list):
  
  # Create timestamp:
  today = datetime.now().astimezone(timezone('Europe/Berlin')).date()
  tomorrow = (today + timedelta(days=1))

  list_for_df = []
  

  # API provides 12hours
  for icao in icao_list:
    times = [["00:00","11:59"],["12:00","23:59"]]

    for time in times:
      url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/{icao}/{tomorrow}T{time[0]}/{tomorrow}T{time[1]}"
      querystring = {"withLeg":"true","withCancelled":"false","withCodeshared":"true","withCargo":"true","withPrivate":"true","withLocation":"false"}
      headers = {
          "X-RapidAPI-Key": "b7c3d136e9msh33795cfe77db702p1d08b1jsn1f39bb3b492e",
          "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com"
          }

      # make request
      response = requests.request("GET", url, headers=headers, params=querystring)

      # format scraped data into JSON format
      flights_json = response.json()
      

      # empty dictionary
      flights_dict = {}

      for flight in flights_json['arrivals']:
        flights_dict['arrival_icao'] = icao
        flights_dict['arrival_time_local'] = flight['arrival'].get('scheduledTimeLocal', None)
        flights_dict['arrival_terminal'] = flight['arrival'].get('terminal', None)
        flights_dict['departure_city'] = flight['departure']['airport'].get('name', None)
        flights_dict['departure_icao'] = flight['departure']['airport'].get('icao', None)
        flights_dict['departure_time_local'] = flight['departure'].get('scheduledTimeLocal', None)
        flights_dict['airline'] = flight['airline'].get('name', None)
        flights_dict['flight_number'] = flight.get('number', None)
        flights_dict['data_retrieved_on'] = datetime.now().astimezone(timezone('Europe/Berlin')).date()
        list_for_df.append(flights_dict)

  return pd.DataFrame(list_for_df)

## FLIGHTS DATAFRAME

In [ ]:
# select the icaos in our list: 'Berlin', 'Hamburg', 'London', 'Istanbul', 'Barcelona'
icaos = ['EDDB', 'EDDH', 'EGLC', 'EGKK', 'EGSS', 'EGLL', 'EGGW', 'LTFM', 'LTFJ', 'LEBL']

# use the function
flights_df = tomorrows_flight_arrivals(icaos)

In [ ]:
flights_df

,arrival_icao,arrival_time_local,arrival_terminal,departure_city,departure_icao,departure_time_local,airline,flight_number,data_retrieved_on
0,EDDB,2023-02-11 11:30+01:00,1,Paris,LFPG,2023-02-11 09:40+01:00,easyJet,U2 5652,2023-02-10
1,EDDB,2023-02-11 11:30+01:00,1,Paris,LFPG,2023-02-11 09:40+01:00,easyJet,U2 5652,2023-02-10
2,EDDB,2023-02-11 11:30+01:00,1,Paris,LFPG,2023-02-11 09:40+01:00,easyJet,U2 5652,2023-02-10
3,EDDB,2023-02-11 11:30+01:00,1,Paris,LFPG,2023-02-11 09:40+01:00,easyJet,U2 5652,2023-02-10
4,EDDB,2023-02-11 11:30+01:00,1,Paris,LFPG,2023-02-11 09:40+01:00,easyJet,U2 5652,2023-02-10
...,...,...,...,...,...,...,...,...,...
4419,LEBL,2023-02-11 22:35+01:00,1,London,EGKK,2023-02-11 19:35+00:00,Vueling,VY 7825,2023-02-10
4420,LEBL,2023-02-11 22:35+01:00,1,London,EGKK,2023-02-11 19:35+00:00,Vueling,VY 7825,2023-02-10
4421,LEBL,2023-02-11 22:35+01:00,1,London,EGKK,2023-02-11 19:35+00:00,Vueling,VY 7825,2023-02-10
4422,LEBL,2023-02-11 22:35+01:00,1,London,EGKK,2023-02-11 19:35+00:00,Vueling,VY 7825,2023-02-10
4423,LEBL,2023-02-11 22:35+01:00,1,London,EGKK,2023-02-11 19:35+00:00,Vueling,VY 7825,2023-02-10

In [ ]:
airports_df

,icao,iata,name,shortName,municipalityName,countryCode,location.lat,location.lon
0,EDDB,BER,"Berlin, Berlin Brandenburg",Brandenburg,Berlin,DE,52.351390,13.493889
1,EDDH,HAM,Hamburg,Hamburg,Hamburg,DE,53.630400,9.988229
5,EGLC,LCY,"London, London City",City,London,GB,51.505300,0.055277
7,EGKK,LGW,"London, London Gatwick",Gatwick,London,GB,51.148100,-0.190277
8,EGSS,STN,"London, London Stansted",Stansted,London,GB,51.885000,0.234999
9,EGLL,LHR,"London, London Heathrow",Heathrow,London,GB,51.470600,-0.461941
10,EGGW,LTN,"London, London Luton",Luton,London,GB,51.874700,-0.368333
11,LTFM,IST,Istanbul,Istanbul,Istanbul,TR,41.275276,28.751944
12,LTFJ,SAW,"Istanbul, Sabiha Gökçen",Sabiha Gökçen,Istanbul,TR,40.898600,29.309200
13,LEBL,BCN,Barcelona,Barcelona,Barcelona,ES,41.297100,2.078459

# 3) SAVE DATAFRAMES

In [ ]:
from google.colab import files

flights_df.to_csv("flights_df.csv", index=False)
files.download("flights_df.csv")

airports_df.to_csv("airports_df.csv", index=False)
files.download("airports_df.csv")